- test_yaml_json.py
- yaml-json-interoperability.yaml
- provides some interoperability test between yaml and json.
> Preliminary interoperability test between yaml and json.

- draft-ietf-httpapi-rest-api-mediatypes.md
> Fix: #13. Add +yaml suffix.

- draft-ietf-httpapi-rest-api-mediatypes.md
- editorial wrapping of http messages
- not sure this is readable... :thinking: :thinking: :thinking:   please take a look at the rendering in TXT/HTML and have your say
> Editorial wrapping.

- draft-ietf-httpapi-rest-api-mediatypes.md
> Fix: #23. YAML evolving.

- draft-ietf-httpapi-yaml-mediatypes.md
- editorial cleanup before publication of -00
> Editorial cleanup

- draft-ietf-httpapi-yaml-mediatypes.md
Fix typical media type template problems
Typos
> YAML Media type template

- draft-ietf-httpapi-rest-api-mediatypes.md
- draft-ietf-httpapi-yaml-mediatypes.md
see https://github.com/httpwg/http-extensions/commit/85c26b8acdd60a188ffa5752877cc4bff82c604a
> Use venue keyword.

- draft-ietf-httpapi-yaml-mediatypes.md
> Fix: #60. s/named anchor/anchor names/

- draft-ietf-httpapi-yaml-mediatypes.md
> Fix: #68. yaml is the preferred extension.

- draft-ietf-httpapi-yaml-mediatypes.md
> Genart minor edits See #83.

- draft-ietf-httpapi-yaml-mediatypes.md
> Artart review: minor edits. See #80.

- draft-ietf-httpapi-yaml-mediatypes.md
> Registration is independent of YAML version. See #79.

- draft-ietf-httpapi-yaml-mediatypes.md
- Change Controller is IETF
Fix: #90
> Fix: #90. Change controller is IETF.

- draft-ietf-httpapi-yaml-mediatypes.md
- adds references to thisrfc in yaml-mediatypes
> Fix: #94. References to [thisrfc] in YAML.

- draft-ietf-httpapi-yaml-mediatypes.md
- fixes typos
- acknowledge @cabo
> YAML typos

- draft-ietf-httpapi-yaml-mediatypes.md
> Fix: #97. YAML booleans

- draft-ietf-httpapi-yaml-mediatypes.md
- editorial improvements of YAML inline
- clarify booleans upon AD request
> Fix: #101, #100. Clarify booleans.

- draft-ietf-httpapi-jsonschema-mediatypes.md
> Add Jason as an author for JSON Schema media type spec

- .github/workflows/ghpages.yml
- .github/workflows/publish.yml
> Bump: upload-artifact v4

- draft-ietf-httpapi-rest-api-mediatypes.md
- mention deprecated alias names
- Fix: #115 
@darrelmiller are there further alias names to mention here?
> Fix: #115. Mention deprecated alias names.

- draft-ietf-httpapi-rest-api-mediatypes.md
- fixes #119 
- split long lines
> Fix: #119. Mention interoperability considerations in registration.

- draft-ietf-httpapi-rest-api-mediatypes.md
> Due diligence: parameter syntax. See #25.
